### ISSUE TITLE
Could you please tell me how to converter a milkdrop preset to butterchurn?

### ISSUE THREAD

**Issue by lexterror** [jberg/milkdrop-preset-converter#2]
Hi, I would like to convert 1 preset to butterchurn, could you please help?

Is there somewhere online I can convert?

This is my preset: http://www.mediafire.com/file/nvx3v9uo65ituvx/LuxXx_-_MoltenWheel_i_-_Isosceles_edit9.milk/file

Thank you!

**Comment by jberg** [comment]
Hi,

I tested it out and if you drag that milkdrop file into the visualizer window on [webamp](https://webamp.org), it will convert the preset in browser and render:

![Screen Shot 2020-08-27 at 9 17 54 PM](https://user-images.githubusercontent.com/428650/91520744-ead2f680-e8aa-11ea-8870-912750759396.png)

Does that work for what you are trying?

Cheers,

Jordan

**Comment by lexterror** [comment]
Thanks very much!

**Comment by lexterror** [comment]
jberg it doesn't work either on Firefox or Google Chrome. I tried dragging the file into the window/viz of webamp.org and it won't convert or render. Is there a trick?

Thank you!

**Comment by jberg** [comment]
It should work in both Firefox and Chrome (but not Safari).

If you hit 'L' while highlighting the Milkdrop window, you will see the listings of presets, it should be at the bottom:

![Screen Shot 2020-09-01 at 7 45 39 PM](https://user-images.githubusercontent.com/428650/91926348-ebdd9c80-ec8b-11ea-98a0-be2068898110.png)

**Comment by lexterror** [comment]
Hi jberg,

Is there any possibility of telling users how to use their own presets. I'm really concerned that a very few people have the information needed to use their own presets. The preset above works very well I don't mind trying to convert it. But it seems the builtin presets are "hardcoded" to the butterchurnPresets.min. Could you please tell me how to use one of your "json" converted presets. Thank you!

**Comment by jberg** [comment]
> Hi jberg,
> 
> Is there any possibility of telling users how to use their own presets. I'm really concerned that a very few people have the information needed to use their own presets. The preset above works very well I don't mind trying to convert it. But it seems the builtin presets are "hardcoded" to the butterchurnPresets.min. Could you please tell me how to use one of your "json" converted presets. Thank you!

Hi!

If you already have a JSON preset, loading it should be as easy as calling `loadPreset` on the visualizer object.  Converting milkdrop presets to the JSON format is unfortunately a harder process.

I'm planning on updating my [converter](https://github.com/jberg/milkdrop-preset-converter-node) to use a Docker container, as currently its not building in most environments. Once thats accomplished it should hopefully be possible to use that to convert presets.

Just as an aside, the main barrier for easily converting milkdrop presets to butterchurn JSON format is the necessity of converting the original milkdrop HLSL shader code into GLSL so it can run in the browser. Thats why I can't just load a milkdrop preset directly :-/

**Comment by eusolomax** [comment]
Hello @jberg , first of all thanks for the amazing work! There is any updates on that ``converting milkdrop presets to butterchurn JSON`` feature?
